// Can a high-priority short kernel cut into a long CTA queue?
#include <cuda_runtime.h>
#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <vector>
#include <unistd.h>
#define CK(x) do{cudaError_t e=(x);if(e!=cudaSuccess){fprintf(stderr,"CUDA: %s line %d\n",cudaGetErrorString(e),__LINE__);exit(1);}}while(0)
constexpr int T=256,CHUNK=16384;
__global__ void traffic(const uint4*p,size_t n,int rounds,unsigned long long*out){size_t chunks=n/CHUNK;uint4 a{0,0,0,0};for(int r=0;r<rounds;++r){size_t base=((blockIdx.x+size_t(r)*gridDim.x)%chunks)*CHUNK;for(int i=threadIdx.x;i<CHUNK;i+=T){uint4 v=p[base+i];a.x+=v.x+r;a.y+=v.y;a.z+=v.z;a.w+=v.w;}}if((threadIdx.x&31)==0)atomicAdd(out,(unsigned long long)(a.x+a.y+a.z+a.w));}
float alone(cudaStream_t s,const uint4*p,size_t n,unsigned long long*out){cudaEvent_t a,b;cudaEventCreate(&a);cudaEventCreate(&b);std::vector<float>v;for(int i=0;i<7;++i){cudaEventRecord(a,s);traffic<<<20,T,0,s>>>(p,n,8,out);cudaEventRecord(b,s);cudaEventSynchronize(b);float x;cudaEventElapsedTime(&x,a,b);v.push_back(x);}std::sort(v.begin(),v.end());return v[0];}
float contend(cudaStream_t bg,cudaStream_t fg,const uint4*p,size_t n,unsigned long long*out,int bg_blocks,int bg_rounds){cudaEvent_t a,b;cudaEventCreate(&a);cudaEventCreate(&b);std::vector<float>v;for(int i=0;i<7;++i){traffic<<<bg_blocks,T,0,bg>>>(p,n,bg_rounds,out);usleep(500);cudaEventRecord(a,fg);traffic<<<20,T,0,fg>>>(p,n,8,out);cudaEventRecord(b,fg);cudaEventSynchronize(b);float x;cudaEventElapsedTime(&x,a,b);v.push_back(x);cudaStreamSynchronize(bg);}std::sort(v.begin(),v.end());return v[0];}
int main(int argc,char**argv){int dev=argc>1?atoi(argv[1]):0;CK(cudaSetDevice(dev));int low,high;CK(cudaDeviceGetStreamPriorityRange(&low,&high));cudaStream_t normal_bg,normal_fg,low_s,high_s;cudaStreamCreateWithPriority(&normal_bg,cudaStreamNonBlocking,0);cudaStreamCreateWithPriority(&normal_fg,cudaStreamNonBlocking,0);cudaStreamCreateWithPriority(&low_s,cudaStreamNonBlocking,low);cudaStreamCreateWithPriority(&high_s,cudaStreamNonBlocking,high);size_t bytes=256ull<<20;uint4*p;unsigned long long*out;cudaMalloc(&p,bytes);cudaMalloc(&out,8);cudaMemset(p,1,bytes);cudaMemset(out,0,8);float a=alone(normal_fg,p,bytes/16,out),same=contend(normal_bg,normal_fg,p,bytes/16,out,2000,8),prio=contend(low_s,high_s,p,bytes/16,out,2000,8),resident_same=contend(normal_bg,normal_fg,p,bytes/16,out,20,800),resident_prio=contend(low_s,high_s,p,bytes/16,out,20,800);printf("priority_low=%d priority_high=%d\n",low,high);printf("case,foreground_ms,slowdown_vs_alone\nalone,%.4f,1.000\nsame_priority_many_ctas,%.4f,%.3f\nhigh_over_low_many_ctas,%.4f,%.3f\nsame_priority_1cta_sm,%.4f,%.3f\nhigh_over_low_1cta_sm,%.4f,%.3f\n",a,same,same/a,prio,prio/a,resident_same,resident_same/a,resident_prio,resident_prio/a);unsigned long long h;cudaMemcpy(&h,out,8,cudaMemcpyDeviceToHost);printf("observable_sink=%llu\n",h);cudaFree(out);cudaFree(p);cudaStreamDestroy(high_s);cudaStreamDestroy(low_s);cudaStreamDestroy(normal_fg);cudaStreamDestroy(normal_bg);}
