// Bulk async unicast versus cluster multicast delivery.
#include <cuda_runtime.h>
#include <cooperative_groups.h>
#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <vector>
namespace cg=cooperative_groups;
#define CK(x) do{cudaError_t e=(x);if(e!=cudaSuccess){fprintf(stderr,"CUDA: %s line %d\n",cudaGetErrorString(e),__LINE__);exit(1);}}while(0)
constexpr int BYTES=1024;
__device__ __forceinline__ unsigned sa(const void*p){return(unsigned)__cvta_generic_to_shared(p);}
__device__ __forceinline__ void waitbar(unsigned b,unsigned ph){asm volatile("{.reg .pred p; W%=: mbarrier.try_wait.parity.shared::cta.b64 p,[%0],%1; @!p bra.uni W%=;}"::"r"(b),"r"(ph):"memory");}
template<bool MC>__global__ void bulk(const char*src,size_t tiles,unsigned cs,unsigned long long*out){__shared__ __align__(128) char sm[BYTES];__shared__ __align__(8) unsigned long long bar64;cg::cluster_group cl=cg::this_cluster();unsigned rank=cl.block_rank();if(threadIdx.x==0)asm volatile("mbarrier.init.shared::cta.b64 [%0],1;"::"r"(sa(&bar64)):"memory");asm volatile("fence.proxy.async.shared::cta;":::"memory");cl.sync();if(threadIdx.x==0){unsigned b=sa(&bar64),phase=0;size_t cid=blockIdx.x/cs,nc=gridDim.x/cs;for(size_t t=cid;t<tiles;t+=nc){asm volatile("mbarrier.arrive.expect_tx.shared::cta.b64 _,[%0],%1;"::"r"(b),"r"(BYTES):"memory");if constexpr(MC){if(rank==0){unsigned short mask=(1u<<cs)-1;asm volatile("cp.async.bulk.shared::cluster.global.mbarrier::complete_tx::bytes.multicast::cluster [%0],[%1],%2,[%3],%4;"::"r"(sa(sm)),"l"(src+t*BYTES),"r"(BYTES),"r"(b),"h"(mask):"memory");}}else asm volatile("cp.async.bulk.shared::cluster.global.mbarrier::complete_tx::bytes [%0],[%1],%2,[%3];"::"r"(sa(sm)),"l"(src+t*BYTES),"r"(BYTES),"r"(b):"memory");waitbar(b,phase);phase^=1;}atomicAdd(out,(unsigned long long)*(unsigned*)sm);}cl.sync();}
template<bool MC>void launch(int grid,int cs,const char*src,size_t tiles,unsigned long long*out){cudaLaunchConfig_t c{};c.gridDim=grid;c.blockDim=32;cudaLaunchAttribute a{};a.id=cudaLaunchAttributeClusterDimension;a.val.clusterDim.x=cs;a.val.clusterDim.y=a.val.clusterDim.z=1;c.attrs=&a;c.numAttrs=1;CK(cudaLaunchKernelEx(&c,bulk<MC>,src,tiles,(unsigned)cs,out));}
template<bool MC>double best(int grid,int cs,const char*src,size_t tiles,unsigned long long*out){cudaEvent_t a,b;cudaEventCreate(&a);cudaEventCreate(&b);launch<MC>(grid,cs,src,tiles,out);CK(cudaDeviceSynchronize());std::vector<float>v;for(int i=0;i<7;++i){cudaEventRecord(a);launch<MC>(grid,cs,src,tiles,out);cudaEventRecord(b);cudaEventSynchronize(b);float x;cudaEventElapsedTime(&x,a,b);v.push_back(x);}std::sort(v.begin(),v.end());cudaEventDestroy(a);cudaEventDestroy(b);return v[0];}
int main(int argc,char**argv){int dev=argc>1?atoi(argv[1]):0;CK(cudaSetDevice(dev));cudaDeviceProp p{};CK(cudaGetDeviceProperties(&p,dev));CK(cudaFuncSetAttribute(bulk<false>,cudaFuncAttributeNonPortableClusterSizeAllowed,1));CK(cudaFuncSetAttribute(bulk<true>,cudaFuncAttributeNonPortableClusterSizeAllowed,1));size_t bytes=256ull<<20,tiles=bytes/BYTES;char*src;unsigned long long*out;CK(cudaMalloc(&src,bytes));CK(cudaMalloc(&out,8));CK(cudaMemset(src,1,bytes));CK(cudaMemset(out,0,8));if(argc>2){int cs=argc>3?atoi(argv[3]):2,grid=(p.multiProcessorCount/cs)*cs;double ms;if(!strcmp(argv[2],"unicast"))ms=best<false>(grid,cs,src,tiles,out);else if(!strcmp(argv[2],"multicast"))ms=best<true>(grid,cs,src,tiles,out);else{fprintf(stderr,"mode must be unicast or multicast\n");return 2;}size_t source=!strcmp(argv[2],"multicast")?bytes:bytes*cs,delivered=bytes*cs;printf("mode,cluster_size,source_GBps,delivered_GBps,time_ms\n%s,%d,%.2f,%.2f,%.4f\n",argv[2],cs,source/(ms*1e6),delivered/(ms*1e6),ms);}else{printf("cluster_size,unicast_source_GBps,multicast_source_GBps,multicast_delivered_GBps,unicast_ms,multicast_ms\n");for(int cs:{2,4,8}){int grid=(p.multiProcessorCount/cs)*cs;double u=best<false>(grid,cs,src,tiles,out),m=best<true>(grid,cs,src,tiles,out);printf("%d,%.2f,%.2f,%.2f,%.4f,%.4f\n",cs,bytes*cs/(u*1e6),bytes/(m*1e6),bytes*cs/(m*1e6),u,m);}}unsigned long long h;CK(cudaMemcpy(&h,out,8,cudaMemcpyDeviceToHost));printf("observable_sink=%llu\n",h);cudaFree(out);cudaFree(src);}
