// Two-stream global-memory interference and overlap matrix.
#include <cuda_runtime.h>
#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <vector>
#define CK(x) do{cudaError_t e=(x);if(e!=cudaSuccess){fprintf(stderr,"CUDA: %s line %d\n",cudaGetErrorString(e),__LINE__);exit(1);}}while(0)
constexpr int T=256;
__global__ void rd(const uint4*p,size_t n,unsigned long long*out){uint4 a{0,0,0,0};for(size_t i=blockIdx.x*T+threadIdx.x;i<n;i+=size_t(gridDim.x)*T){uint4 v=p[i];a.x^=v.x;a.y^=v.y;a.z^=v.z;a.w^=v.w;}if((threadIdx.x&31)==0)atomicAdd(out,(unsigned long long)(a.x+a.y+a.z+a.w));}
__global__ void wr(uint4*p,size_t n,unsigned seed){uint4 v{seed,seed+1,seed+2,seed+3};for(size_t i=blockIdx.x*T+threadIdx.x;i<n;i+=size_t(gridDim.x)*T)p[i]=v;}
__global__ void cp(const uint4*a,uint4*b,size_t n){for(size_t i=blockIdx.x*T+threadIdx.x;i<n;i+=size_t(gridDim.x)*T)b[i]=a[i];}
struct M{float wall,a,b;};
template<class A,class B>M measure(cudaStream_t s1,cudaStream_t s2,cudaStream_t ctl,A a,B b){std::vector<M>v;for(int r=0;r<8;++r){cudaEvent_t st,e1,e2,en;cudaEventCreate(&st);cudaEventCreate(&e1);cudaEventCreate(&e2);cudaEventCreate(&en);cudaEventRecord(st,ctl);cudaStreamWaitEvent(s1,st);cudaStreamWaitEvent(s2,st);a(s1);b(s2);cudaEventRecord(e1,s1);cudaEventRecord(e2,s2);cudaStreamWaitEvent(ctl,e1);cudaStreamWaitEvent(ctl,e2);cudaEventRecord(en,ctl);cudaEventSynchronize(en);float x,y,z;cudaEventElapsedTime(&x,st,en);cudaEventElapsedTime(&y,st,e1);cudaEventElapsedTime(&z,st,e2);if(r)v.push_back({x,y,z});cudaEventDestroy(st);cudaEventDestroy(e1);cudaEventDestroy(e2);cudaEventDestroy(en);}std::sort(v.begin(),v.end(),[](M x,M y){return x.wall<y.wall;});return v[0];}
int main(int argc,char**argv){int dev=argc>1?atoi(argv[1]):0;CK(cudaSetDevice(dev));cudaDeviceProp p{};CK(cudaGetDeviceProperties(&p,dev));size_t bytes=256ull<<20,n=bytes/16;uint4 *a,*b,*c,*d;unsigned long long*out;CK(cudaMalloc(&a,bytes));CK(cudaMalloc(&b,bytes));CK(cudaMalloc(&c,bytes));CK(cudaMalloc(&d,bytes));CK(cudaMalloc(&out,8));cudaMemset(a,1,bytes);cudaMemset(b,2,bytes);cudaMemset(c,3,bytes);cudaMemset(d,4,bytes);cudaMemset(out,0,8);cudaStream_t s1,s2,ctl;cudaStreamCreate(&s1);cudaStreamCreate(&s2);cudaStreamCreate(&ctl);int blocks=p.multiProcessorCount*8;
 auto R1=[&](cudaStream_t s){rd<<<blocks,T,0,s>>>(a,n,out);};auto R2=[&](cudaStream_t s){rd<<<blocks,T,0,s>>>(b,n,out);};auto W1=[&](cudaStream_t s){wr<<<blocks,T,0,s>>>(c,n,7);};auto W2=[&](cudaStream_t s){wr<<<blocks,T,0,s>>>(d,n,9);};auto C1=[&](cudaStream_t s){cp<<<blocks,T,0,s>>>(a,c,n);};auto C2=[&](cudaStream_t s){cp<<<blocks,T,0,s>>>(b,d,n);};auto N=[](cudaStream_t){};
 M r=measure(s1,s2,ctl,R1,N),w=measure(s1,s2,ctl,W1,N),c0=measure(s1,s2,ctl,C1,N);printf("single_read_ms=%.4f single_write_ms=%.4f single_copy_ms=%.4f\n",r.wall,w.wall,c0.wall);printf("pair,stream1_ms,stream2_ms,wall_ms,serial_over_wall,total_fabric_GBps\n");auto show=[&](const char*n,M m,double serial,double fabric){printf("%s,%.4f,%.4f,%.4f,%.3f,%.2f\n",n,m.a,m.b,m.wall,serial/m.wall,fabric*bytes/(m.wall*1e6));};show("read+read",measure(s1,s2,ctl,R1,R2),2*r.wall,2);show("read+write",measure(s1,s2,ctl,R1,W2),r.wall+w.wall,2);show("write+write",measure(s1,s2,ctl,W1,W2),2*w.wall,2);show("copy+read",measure(s1,s2,ctl,C1,R2),c0.wall+r.wall,3);show("copy+copy",measure(s1,s2,ctl,C1,C2),2*c0.wall,4);unsigned long long h;cudaMemcpy(&h,out,8,cudaMemcpyDeviceToHost);printf("observable_sink=%llu\n",h);cudaStreamDestroy(ctl);cudaStreamDestroy(s2);cudaStreamDestroy(s1);cudaFree(out);cudaFree(d);cudaFree(c);cudaFree(b);cudaFree(a);}
